# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          7.0.x
          8.0.x
          9.0.x
    - name: Restore dependencies(.NET 7)
      run: dotnet restore LessCode.EFCore.StronglyTypedId.sln
    - name: Build(.NET 7)
      run: dotnet build LessCode.EFCore.StronglyTypedId.sln --no-restore
    - name: Test(.NET 7)
      run: dotnet test LessCode.EFCore.StronglyTypedId.sln --no-build --verbosity normal
    - name: Restore dependencies(.NET 8)
      run: dotnet restore LessCode.EFCore.StronglyTypedId.NET8.sln
    - name: Build(.NET 8)
      run: dotnet build LessCode.EFCore.StronglyTypedId.NET8.sln --no-restore
    - name: Test(.NET 8)
      run: dotnet test LessCode.EFCore.StronglyTypedId.NET8.sln --no-build --verbosity normal
    - name: Restore dependencies(.NET 9)
      run: dotnet restore LessCode.EFCore.StronglyTypedId.NET9.sln
    - name: Build(.NET 9)
      run: dotnet build LessCode.EFCore.StronglyTypedId.NET9.sln --no-restore
    - name: Test(.NET 9)
      run: dotnet test LessCode.EFCore.StronglyTypedId.NET9.sln --no-build --verbosity normal
